#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Windows EFI" {
	search --fs-uuid --no-floppy --set=root 3AFE-56B7
	chainloader (${root})/efi/Boot/bootx64.efi
}
